import * as MeyaOutline from "meya-icons/react/outline";
import type { MeyaIcon, MeyaIconProps } from "meya-icons/react/outline";
import { PAGE_ICON_NAMES } from "@/lib/domain/schema";

export const {
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  Archive,
  ArrowRight,
  Calendar,
  CheckCircle: CheckCircle2,
  CheckCircle: CheckSquare,
  ChevronLeft,
  ChevronRight,
  Clock,
  Compass,
  Copy,
  Download,
  ExpandDiagonal: ExternalLink,
  Email: Mail,
  Grid: Layout,
  Grid: LayoutGrid,
  Landmark: Building2,
  Layers,
  List,
  ListNumbered: ListOrdered,
  Logout: LogOut,
  MapPin,
  Megaphone,
  Message: Quote,
  Microphone,
  Minus,
  Moon,
  Plus,
  Refresh: Loader2,
  Refresh: RefreshCw,
  RotateLeft: RotateCcw,
  Rows: GripVertical,
  Search,
  Settings,
  Sidebar: PanelLeftClose,
  SpreadsheetFile: FileSpreadsheet,
  Star,
  Suitcase: Briefcase,
  Sun,
  Schedule: CalendarClock,
  BarChart: BarChart3,
  Book: Heading2,
  Code: Code2,
  Code: FileCode2,
  DataTable: Table2,
  Document: FileText,
  Document: Type,
  Documentation: Heading3,
  Edit: Pencil,
  Folder,
  History,
  Inbox,
  InfoCircle,
  Landmark,
  MessageSquare,
  Phone,
  Square,
  Star: Sparkles,
  TrendUp: TrendingUp,
  Trash: Trash2,
  Upload,
  VideoCamera: Video,
  WorldTime: Globe,
  Attachment: Link2,
  Assignment: Heading1,
  CheckCircle,
  Check,
  ChevronsDown,
  ChevronsUp,
  Document,
  Email,
  ExpandDiagonal,
  Refresh,
  RotateLeft,
  Suitcase,
  TrendUp,
  VideoCamera,
  WorldTime,
  X,
} = MeyaOutline;

export type MeyaIconName = keyof typeof MeyaOutline;

export const PAGE_ICON_OPTIONS = [
  { name: "Document", label: "Dokumen" },
  { name: "Folder", label: "Folder" },
  { name: "Suitcase", label: "Koper" },
  { name: "Book", label: "Buku" },
  { name: "Star", label: "Bintang" },
  { name: "Calendar", label: "Kalender" },
  { name: "CheckCircle", label: "Checklist" },
  { name: "InfoCircle", label: "Informasi" },
  { name: "BarChart", label: "Statistik" },
  { name: "Email", label: "Surat" },
  { name: "Code", label: "Kode" },
  { name: "Archive", label: "Arsip" },
] as const satisfies readonly { name: (typeof PAGE_ICON_NAMES)[number] & MeyaIconName; label: string }[];

const iconRegistry = MeyaOutline as unknown as Record<string, MeyaIcon>;

export function ProjectIcon({
  name,
  fallback = "Document",
  ...props
}: Omit<MeyaIconProps, "name"> & { name?: string | null; fallback?: MeyaIconName }) {
  const Icon = iconRegistry[name ?? ""] ?? iconRegistry[fallback] ?? iconRegistry.Document;
  return <Icon aria-hidden="true" {...props} />;
}
